### ISSUE TITLE
New Zealand maps

### ISSUE THREAD

**Issue by dakvid** [pvictor/topogRam#3]
Would it be possible to add New Zealand maps? I tried to have a go myself, but the topojson files I created threw errors.

There are shape files [available from Statistics NZ](http://www.stats.govt.nz/browse_for_stats/Maps_and_geography/Geographic-areas/digital-boundary-files.aspx)

I grabbed the "New Zealand 2017 clipped generalised" file to get territorial authorities (TA) and regional councils (REGC), and "New Zealand Electoral Districts 2014" to get the general (GED) and Māori (MED) electorates, as we've just had an election (though annoyingly these are to the 12 nautical mile boundary at the coast).

**Comment by dakvid** [comment]
Should mention I'm happy to have another go myself if there are guidelines that might help me figure out where I went wrong. :-)

**Comment by dakvid** [comment]
Hi Victor. Thanks for the reply. No worries about the delay - it was just one of several options I wanted to explore last year, with not much time to do it. I'll be better prepared for the next election. :-)

I noticed that you added a New Zealand regions shape in there, but haven't gotten that to work. I don't see any output, but perhaps I just need to figure out the correct origin settings. I can't remember what issues I had when I tried last year to add my own shapes, but I didn't get far when I had a quick trial this time. Perhaps it's a similar issue with origins, but it may be a factor that the TopoJSON I'm creating with geojsonio has a bbox object and no transform object (??).

r2d3maps looks interesting! I've managed to run your example code (though the tooltips are empty in the first one, and the multiple option switching doesn't seem to work in the second) and look forward to trying it out with my own shape files.

Thanks!

**Comment by dakvid** [comment]
To update, the r2d3maps tooltips were only blank in RStudio viewer - they displayed fine in a real browser. (The multiple value example still didn't work in a browser though.)

And I managed to get the topogRam included nz-reg to work using the following code:
```
topogRam(
  data = data.frame(
    id = c(0:15),
    NAME = c(as.character(0:15)),
    my_data = as.integer(runif(16, min = 100, max = 1000)),
    my_other_data = as.integer(runif(16, min = 100, max = 1000))
  ),
  key_var = c("my_data", "my_other_data"),
  shape = "nz-reg",
  geo_lab = "NAME",
  width = 500, height = 500,
  origin = c(-4500, -850),
  scale = 10000
)
```

However in coming to write this comment I see you've updated and refactored the package. It looks like a simpler and more generic interface, which is great! The examples in the readme worked fine for me, but my own attempt didn't work out of the box:
```
library(sf)
library(rmapshaper)
nz_regions <-
  read_sf("statsnzregional-council-2018-clipped-generalised-GPKG/regional-council-2018-clipped-generalised.gpkg") %>% 
  filter(REGC2018_V1_00_NAME != "Area Outside Region") %>% 
  ms_simplify(keep = 0.002, keep_shapes = TRUE)
nzreg$foo <- runif(16, min = 1000, max = 1000000)

topogRam(
  shape = nzreg,
  value = "foo"
)
```
Have I missed something here, or have I run into an edge case? (Data from [Stats NZ](https://datafinder.stats.govt.nz/layer/92205-regional-council-2018-clipped-generalised/))

**Comment by pvictor** [comment]
Hi David,
Thanks for your feedback on {r2d3maps}, indeed i have some trouble with compatibility between RStudio viewer and browser...

And yes I decided to completely rewrite {topogRam} to use a wonderful wrapper of topogram.js (https://github.com/vasturiano/cartogram-chart). I'm going to add features this week, and for now it doesn't work in RStudio viewer (I'll try with pre-release.

Your example doesn't work for now, it only support Mercator projection, this works if you change CRS (I used shapefiles from the link you provided) : 

```r
library(sf)
library(rmapshaper)
library(topogRam)
library(dplyr)

nz_regions <-
  read_sf("statsnzregional-council-2018-clipped-generalised-SHP/regional-council-2018-clipped-generalised.shp") %>% 
  filter(REGC2018_1 != "Area Outside Region") %>% 
  st_transform(crs = 4326) %>%  # here change crs
  ms_simplify(keep = 0.002, keep_shapes = TRUE)
nz_regions$foo <- floor(runif(16, min = 1000, max = 1000000))

topogRam(
  shape = nz_regions,
  value = "foo", 
  tooltip_label = ~REGC2018_1,
  n_iteration = 40
)
```
![image](https://user-images.githubusercontent.com/4415580/46276613-edaefa80-c560-11e8-953e-fad43fc2139c.png)

Victor

**Comment by dakvid** [comment]
Ah, brilliant, thanks. I've transformed them to Mercator ("+proj=longlat +datum=WGS84", which is the same as 4326 I think) when creating TopoJSON files previously, so probably should have thought to do that here too.

It works great now - I look forward to the planned features. Thanks heaps this package!

**Comment by pvictor** [comment]
The select menu is back, here an example in markdown : https://pvictor.github.io/NZ-topogRam/

Next features planned : 

 * Proxy method for shiny apps
 * Legend
 * labs
 * Projections sf <> D3

(Feel free to close this issue if you want 😄 )

Victor

**Comment by dakvid** [comment]
Awesome. Yes, you've truly solved the original "issue" now. Thanks! :-)
